### ISSUE TITLE
How to resolve collision with keybinding + mouse action?

### ISSUE THREAD

**Issue by n3bulous** [atom/keybinding-resolver#19]
I use Sublime Style Column Selection and something else is colliding with the alt-mouse-select.  I want to say it is ctags, but I can't find any keybindings that use the mouse to verify.

Any thoughts?

**Comment by thomasjo** [comment]
Atom doesn't support mouse-based keybindings yet, which I suspect you discovered.

**Comment by thomasjo** [comment]
There are a couple of open issues on Atom Core with respect to this feature, that you might want to subscribe to:
https://github.com/atom/atom/issues/2256
https://github.com/atom/atom/issues/2306

**Comment by n3bulous** [comment]
Thanks, Thomas!
