### ISSUE TITLE
Add ability to unset keybinding

### ISSUE THREAD

**Issue by zephraph** [atom/keybinding-resolver#29]
When you have a keybinding conflict it would be useful to have the ability to click an `unset` button or something similar that would add an unset entry for that keybinding to your `keymap.cson` file. 

Something like this:

![unset](https://cloud.githubusercontent.com/assets/3087225/9281768/15200910-428d-11e5-8bb8-3d75e4e0b084.png)

**Comment by glyg** [comment]
+1 for that!=, it would ease a lot the resolving of conflicts (of which I have yet to find a solution...)

**Comment by kandros** [comment]
+1
