### ISSUE TITLE
Add ability to copy command name to clipboard

### ISSUE THREAD

**Issue by shawninder** [atom/keybinding-resolver#30]
I was worried about getting the order of the transform keys wrong, e.g. `ctrl-shift` rather than `shift-ctrl`, so I thought I'd let atom resolve it and copy paste from there. But It's impossible to select the text. If it were, I don't know what would happen when I press `cmd-c`, of course...

Repro:
1. `key-binding-resolver:toggle`
2. press a key
3.Try to select that key as printed by the resolver

**Comment by RomFouq** [comment]
A "copy to clipboard" button would be even better...

**Comment by kandros** [comment]
I pushed a PR a while ago to introduce this behaviour but haven't had a reply yet

https://github.com/atom/keybinding-resolver/pull/34

**Comment by kandros** [comment]
Please consider review #34 in order to have this feature implemented

**Comment by WalterGR** [comment]
This would be _super useful_.  I always forget about the following workaround:

1.  Remember Atom's representation of the relevant key / key combination, at least approximately (e.g. "alt-left" or "alt left" or "left alt").
2.  Open Settings.
3.  Keybindings tab.
4.  Type the representation from step 1.
5.  Click one of the "copy" icons.

This is a pain, and unlike keybinding-resolver, Settings -> Keybindings doesn't show the source file, meaning that the feature sets of the two (beyond the ability to copy to the clipboard) do not overlap when they could.

**Comment by WalterGR** [comment]
Also, regarding the original title change of "Can't select the command printed out by the resolver" to "Add ability to copy command to clipboard":

Adding a special ability isn't necessary, but just making the text selectable would go a long way.
