### ISSUE TITLE
Not resolving ctrl-cmd-p

### ISSUE THREAD

**Issue by adamreisnz** [atom/keybinding-resolver#32]
For the past few days I've been having an issue with atom project-manager not launching anymore after pressing the designated command `ctrl-cmd-p`.

This is the command I'm trying to run:

![ss](https://www.dropbox.com/s/huw60k00pvscwua/Screenshot%202015-09-28%2011.22.46.png?dl=1)

As you can see the key binding is there.
However, when I press it, nothing happens. They key binding resolver is stuck at `ctrl-cmd` and doesn't register the `p`:

![ss](https://www.dropbox.com/s/bwt1aeaasa7pybu/Screenshot%202015-09-28%2011.23.32.png?dl=1)

Any idea what might be happening here? It seems to only affect the `p`.
I have no other commands linked to that key combination as far as I'm aware.

I'm running the latest version of all relevant packages and atom (1.0.19). This is on OS X 10.10.3.

**Comment by adambuczynski** [comment]
Haven't encountered this issue anymore lately so will close for now.

**Comment by adambuczynski** [comment]
I spoke too soon, it happened to me again today, after restarting Atom. `ctrl-cmd-p` unresponsive again.

**Comment by 50Wliu** [comment]
Generally this happens when another app intercepts the keybinding before it reaches Atom.  Check any other programs you have installed.

**Comment by adamreisnz** [comment]
From memory, that wasn't the case. It hasn't happened for a long time though so it's ok to close this issue.
