### ISSUE TITLE
Keybinding not working correctly

### ISSUE THREAD

**Issue by mattberkowitz** [atom/keybinding-resolver#38]
A user of my package, autoclose-html, has reported an issue with a keybinding I added recently https://github.com/mattberkowitz/autoclose-html/issues/128

It seems likely this is largely due to his non-standard setup (QWERTZ keyboard but with a QWERTY configuration, according to his report).  Basically ":" is executing the command bound to ">".

Don't know that anything can really be done about it, but I wanted to report it upstream

**Comment by 50Wliu** [comment]
Yeah non-US keyboards currently aren't supported, though that will hopefully change soon(TM) (or at least, the issue will be unblocked soon).  See atom/atom-keymap#35 for the upstream *upstream* issue.

**Comment by Nikki1993** [comment]
I have a finnish QWERTY keyboard and suffer from the same issue so it's not only US with QWERTY layout.
