### ISSUE TITLE
Cannot resolve "."

### ISSUE THREAD

**Issue by ryaning** [atom/keybinding-resolver#42]
Cannot resolve when pressing the dot key (".") or any combinations with shift- or alt-.

**Comment by 50Wliu** [comment]
Cannot reproduce.  What Atom version are you using and what keyboard layout?

**Comment by ryaning** [comment]
Atom version is 1.9.2 with en_GB keyboard. 

However, the problem is solved after I disabled keyboard-localization package. Now it works well.

**Comment by 50Wliu** [comment]
Thanks for the update!
