### ISSUE TITLE
Heading scrolls

### ISSUE THREAD

**Issue by kevinsawicki** [atom/keybinding-resolver#6]
Super minor but I would expect the heading in the view to not scroll, only the table to scroll, similar to the find and replace results.

![heading-scrolls](https://cloud.githubusercontent.com/assets/671378/3349012/22691352-f94e-11e3-8de2-e4be52082c68.gif)

**Comment by eboracus** [comment]
I don't see any scrolling at all, has something changed with this? I think this pane should be limited in vertical size (with scrolling), I always end up with the editor completely covered if I put in a command that has loads of entries. :/

![key_binding_fullscreen](https://cloud.githubusercontent.com/assets/11758299/8947669/92933cbe-3595-11e5-9942-ea188590981d.png)

**Comment by bluekeys** [comment]
I'm with eboracus on this one. I don't see any scrolling, but would rather I did.

**Comment by 50Wliu** [comment]
Closing as the view is variable-height.
