### ISSUE TITLE
Fix flaky KeyBindingResolverView tests

### ISSUE THREAD

**Issue by daviwil** [atom/keybinding-resolver#60]
While finishing up the work on the [Atom Nightly Releases PR](https://github.com/atom/atom/pull/17538), I've run across a persistent failure when running the keybinding-resolver package tests on VSTS macOS builds.  To finish up that PR, I've had to temporarily disable the following test when running on VSTS:

```
 KeyBindingResolverView
   when a keydown event occurs
     it displays all commands for the keydown event but does not clear for the keyup when there is no keyup binding
       TypeError: Cannot read property 'textContent' of null
         at it (/Users/vsts/agent/2.134.2/work/1/s/node_modules/keybinding-resolver/spec/keybinding-resolver-view-spec.js:91:80)
         at <anonymous>
```

At this time I don't have a clear picture of why this single test would be failing on VSTS since we run many other UI tests that do not fail.  I have seen this test pass twice out of close to 100 runs, so it's likely that there's a subtle timing issue involved.

For now, I'm detecting the `CI_PROVIDER` environment variable that I set on VSTS test runs to skip this test explicitly when the variable is set to `VSTS`.  Once we can diagnose the root cause and get it fixed, this check will be removed.

**Comment by daviwil** [comment]
It appears that this is just a flaky test on Linux and macOS, it fails about half the time on TravisCI.  Since the last work on this package was in late 2017, something must have changed with more recent Atom releases (probably Electron) which causes the timing of key events or Etch redraws to not line up with what these tests expect.

I'll look into the failures in more depth after the Nightly Releases PR is finished.

**Comment by bdowling** [comment]
fwiw, I've run into this twice with a PR I've posted.  Resubmitting the commit with no code changes clears it.  It is finicky.  Is it not waiting for the DOM to settle or something like that?
