### ISSUE TITLE
Doesn't Resolve "/"

### ISSUE THREAD

**Issue by rsanabria** [atom/keybinding-resolver#7]
I have a Latin Keyboard, and for the "/" (Shift + 7) key, the Resolver shows a ?, it works for all the other keys.
I'm working with ElementaryOS and installed Atom Editor from webupd8 repo.
![screenshot from 2014-07-16 00 02 59](https://cloud.githubusercontent.com/assets/5460954/3594792/8ec271fe-0ca6-11e4-8dae-0e07d1543ae2.png)

**Comment by 50Wliu** [comment]
Should be fixed since Atom 1.12.
